### ISSUE TITLE
Add branch to `changelog:unreleased`

### ISSUE THREAD

**Issue by JelmerDV** [markwalet/laravel-changelog#17]
It's useful to see in what branch a changelog line has been added, because the list can get quite big. That way you don't have to search your own branch folder to see what has been added yet

**Comment by markwalet** [comment]
In my opinion, the `changelog:unreleased` command should just render the changelog like it would been rendered in the file itself. Or at least look like it. Printing the branch aside of it wouldn't help that.

Instead, I suggest we create a new command. Something like `changelog:current` which will print all changes for the branch that you are in right now.

**Comment by JelmerDV** [comment]
Well that could work out, or you will just identify each line with a #BRANCH or whatever

**Comment by markwalet** [comment]
The intention of the `changelog:unreleased` method is to see a preview of everything you will release. Putting a branch name after every issue gives too much noise in my opinion.

But I agree that there should be a better way to view your own changes. This will be implemented in https://github.com/markwalet/laravel-changelog/issues/8
