### ISSUE TITLE
Updated template is not used when generating changelog

### ISSUE THREAD

**Issue by megawubs** [markwalet/laravel-changelog#3]
I've altered the published changelog blade template, but when I generate the changelog the old version of the file is still used.

**Comment by markwalet** [comment]
This is weird. Can you try to fix it and send a merge request?

**Comment by megawubs** [comment]
Do I have write access to this repo?

**Comment by markwalet** [comment]
Yes, you have

**Comment by markwalet** [comment]
@megawubs, any updates?

**Comment by megawubs** [comment]
Nope, didn't get to it

**Comment by markwalet** [comment]
I found the issue. The template file is being published to the wrong folder. I will fix this right now.
