### ISSUE TITLE
Issue using GitHub flow

### ISSUE THREAD

**Issue by pedrommone** [markwalet/laravel-changelog#33]
Hello!

I've noticed that the package does not handle well branches that use `/` due to the directory structure, eg:
```
.changes
\_ 0.1.0
  \_ features
    \_ branch-name-here.xml
```

It will simply omit it and give me an empty section on `changelog.md`, eg:

```
# Release Notes


## [Unreleased]

## [01.0]
```

I see two ways to fix that:
- Sanitize the file creation name (replaces `/` by `-`);
- Make the file read recursive.

I can help fix that but now I want to understand what is the best way to handle that.

**Comment by markwalet** [comment]
Thanks for letting me know!

I'll try to make some time free tonight to take a look at it.

**Comment by pedrommone** [comment]
Hey @markwalet, thank you! :) If you need any kind of help, let me know.

**Comment by markwalet** [comment]
My first thought it that I should just allow nested xml files. Two reasons:

- I don't think that there is a disallowed character in branch names that is allowed in path names (to replace the `/` without the chance of making a name collision)
- Nested xml files make it easier to navigate through them manually.

This will be a little bit more work I'm afraid, but ai think it'll be worth it in the end.

**Comment by markwalet** [comment]
I think I fixed it, can you check if the bug still exists on version 1.6.1?

**Comment by pedrommone** [comment]
@markwalet its working very well, thank you :)
