### ISSUE TITLE
Keep `unreleased` folder.

### ISSUE THREAD

**Issue by megawubs** [markwalet/laravel-changelog#4]
I think we should not rename the unreleased folder to the version during a release.

The unreleased folder should be kept, with a .gitignore. Now, auto merging will put items that where in the unreleased folder into the folder it was renamed to during a release. This results in unreleased changed being added to previous versions in the changelog.

**Comment by markwalet** [comment]
You're right. We should test if the git diff works when we keep the gitignore folder. If it does, your solution should work fine. I can try this coming thursday.
