### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by eshimischi** [markwalet/laravel-changelog#52]
[Laravell 11.x](https://github.com/laravel/framework/releases/tag/v11.0.1)

**Comment by markwalet** [comment]
Ah apparently I forgot this package.

I'll try to get to it this week. Hopefully tomorrow. Feel free to create a PR yourself if you have some spare time.

**Comment by eshimischi** [comment]
You have in requirements markwalet/laravel-git-state should also be updated. Ill try to do PRs today

**Comment by markwalet** [comment]
Resolved in [v1.10.0](https://github.com/markwalet/laravel-changelog/releases/tag/v1.10.0)
